version: '2'
services:
  companycontroller-mongodb:
    image: mongo:4.2.7
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/CompanyController/mongodb/:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME={mongodb-username}
      - MONGO_INITDB_ROOT_PASSWORD={mongodb-password}
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8081:1234
    depends_on:
      - companycontroller-mongodb
    environment:
      - HOST=0.0.0.0
